"""add milestone to tasks

Revision ID: 4e3d32cdf2c8
Revises: eb0ace215fb2
Create Date: 2026-06-02 10:21:52.448673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3d32cdf2c8'
down_revision: Union[str, None] = 'eb0ace215fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('milestone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'milestone')
    # ### end Alembic commands ###
